// Generate the site's logo component and favicons from the bear artwork.
//
//   node scripts/gen-logo.mjs [path-to-bear.svg]
//
// The source is a vector of Nuna Parr's sculpture "Dancing Bear" (attribution
// lives in src/site.config.ts and renders in the footer).
//
// The artwork is a solid silhouette: unclassed path(s) with no fill attribute,
// so they inherit the default black. Any internal openings are counter-wound
// subpaths within the same path, so the fill rule handles them — there is
// nothing to composite and no second colour to track.
//
// The one thing this script exists to prevent: an Illustrator re-export can
// arrive as a two-tone drawing instead — a <style> block of .cls-N fill rules
// where a full-canvas white PLATE is the classed path and the animal is the
// unclassed one. That reads as "the classed path is the body", which is
// backwards, and renders a pale square with a bear knocked out of it. If that
// shape ever comes back, the guard below stops the build rather than letting it
// ship, and `git log -- scripts/gen-logo.mjs` has the version that handled it.

import { readFileSync, writeFileSync } from "node:fs";
import sharp from "sharp";

const SRC =
  process.argv[2] ?? "/Users/me/Library/CloudStorage/Dropbox/design/260813-jaan.io-bear/bear.svg";

/** Estonian blue, for the favicon's bear. */
const FAVICON_INK = "#0030DE";
/**
 * The favicon needs its own background: #0030DE against #000 measures 2.48:1,
 * unreadable at 16px, where on white it is 8.48:1 and holds up in both light
 * and dark browser chrome.
 */
const FAVICON_BG = "#ffffff";

const svg = readFileSync(SRC, "utf8");

const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1];
if (!viewBox) throw new Error(`${SRC}: no viewBox`);

if (/<style[\s>]/.test(svg) && /fill\s*:/.test(svg)) {
  throw new Error(
    `${SRC}: this export carries a <style> block with fill rules — the two-tone ` +
      `plate-and-bear shape, not the silhouette this script expects. Read the note at ` +
      `the top of scripts/gen-logo.mjs before changing anything.`,
  );
}

// Keep every path that actually paints. `fill="none"` slivers are trace leftovers.
const bear = [...svg.matchAll(/<path([^>]*?)\/>/g)]
  .filter((m) => !/fill="none"/.test(m[1]))
  .map((m) => m[1].match(/\sd="([^"]*)"/)?.[1])
  .filter(Boolean);

if (!bear.length) throw new Error(`${SRC}: no paintable <path> found`);
console.log(`${bear.length} path(s) → the bear silhouette`);

// ── The Astro component ──────────────────────────────────────────────────────
const component = `---
// The site's logo mark: Nuna Parr, "Dancing Bear".
//
// GENERATED by scripts/gen-logo.mjs — re-run that rather than editing the path
// data by hand. Attribution renders in the footer from SITE.footer.credit
// (src/site.config.ts).
//
// Contract kept from the mark this replaced:
//   • \`class={class}\` and \`aria-hidden="true"\` — the link around it carries the
//     accessible name, so the mark itself stays silent to screen readers
//   • \`currentColor\`, so it follows --text and its hover/focus colour changes
//     for free, and inverts correctly if --bg and --text are ever swapped
//   • a \`viewBox\` — .site-logo in src/styles/chrome.css sizes by height, so the
//     aspect ratio comes from the viewBox, not width/height attributes
interface Props {
  class?: string;
}
const { class: className = "site-logo" } = Astro.props;
---

<svg
  class={className}
  viewBox="${viewBox}"
  xmlns="http://www.w3.org/2000/svg"
  aria-hidden="true"
  focusable="false"
>
${bear.map((d) => `  <path class="bear" d="${d}" />`).join("\n")}
</svg>

<style>
  .bear {
    fill: currentColor;
  }
</style>
`;
writeFileSync("src/components/Logo.astro", component);
console.log("wrote src/components/Logo.astro");

// ── The favicon ──────────────────────────────────────────────────────────────
const faviconSvg =
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}">` +
  `<rect width="100%" height="100%" fill="${FAVICON_BG}"/>` +
  bear.map((d) => `<path fill="${FAVICON_INK}" d="${d}"/>`).join("") +
  `</svg>`;
writeFileSync("public/favicon.svg", faviconSvg + "\n");
console.log("wrote public/favicon.svg");

const buf = Buffer.from(faviconSvg);
await sharp(buf, { density: 600 }).resize(512, 512).png().toFile("public/favicon.png");
await sharp(buf, { density: 600 }).resize(180, 180).png().toFile("public/apple-touch-icon.png");
console.log("wrote public/favicon.png and public/apple-touch-icon.png");
