// ─────────────────────────────────────────────────────────────────────────────
// SITE — everything that makes this site *this* site.
//
// This is the first file to edit when rebranding. Name, description, navigation,
// social links, structured data, and the on/off switches for the optional
// features all live here. Nothing below this file needs editing to rebrand: the
// layout, header, mobile menu, and footer all read from `SITE`.
//
// What is deliberately NOT here (it lives outside the Astro build):
//   • the canonical origin — `site:` in astro.config.mjs
//   • the sitemap line   — public/robots.txt
//   • colors, fonts, spacing — src/styles/tokens.css
//   • the favicons       — public/favicons/*.svg (one portrait glyph per day,
//     picked in src/lib/favicon.ts), plus the composite fallbacks
//     public/favicon.svg, favicon.png, apple-touch-icon.png. All of them are
//     generated by scripts/gen-favicons.mjs; the header is a plain wordmark.
// ─────────────────────────────────────────────────────────────────────────────

/** A navigation or footer link. Set `external` to open in a new tab safely. */
export interface SiteLink {
  label: string;
  href: string;
  external?: boolean;
}

export const SITE = {
  // ── Identity ───────────────────────────────────────────────────────────────
  /** Used in <html lang> and as the base for the title template. */
  lang: "en",
  /** Open Graph locale, e.g. "en_US", "en_GB", "de_DE". */
  locale: "en_US",
  /** Appended to every page title as " | {name}" — see src/layouts/Base.astro. */
  name: "JAAN ALTOSAAR",
  /** Fallback <meta name="description"> for pages that don't set their own. */
  description:
    "Jaan Altosaar on machine learning for health and science, variational inference, and interactive views of large public datasets.",
  /** Browser UI tint on mobile. Usually --bg from tokens.css, or a shade of it. */
  themeColor: "#000000",

  // ── Fonts ──────────────────────────────────────────────────────────────────
  // Preloaded in <head>. Must match the @font-face src URLs in
  // src/styles/fonts.css — see the swap recipe at the top of that file.
  //
  // Only the files EVERY page needs belong here; a preload the page does not go
  // on to use is pure wasted bandwidth, and the browser warns about it.
  //   • HankenGrotesk-latin — the content face (--font-display, --font-body)
  //   • Inter — the chrome face (--font-chrome): nav, mobile menu, footer
  // Deliberately absent: HankenGrotesk-latin-ext, which its unicode-range
  // fetches only when an accented character actually appears, and Fraunces,
  // which no role token names any more.
  //
  // `npm run fonts:check` fails the build if this list and the roles disagree.
  fonts: ["/fonts/HankenGrotesk-latin.woff2", "/fonts/Inter.woff2"],

  // ── Navigation ─────────────────────────────────────────────────────────────
  // One source of truth. The header, the mobile menu, and the footer all read
  // from here, so adding a page means editing this block and nothing else.
  //
  nav: {
    /** Header links, shown to the right of the logo on desktop. */
    header: [
      { label: "Projects", href: "/projects" },
      { label: "Images", href: "/images" },
      { label: "About", href: "/about" },
    ] as SiteLink[],
    /**
     * The single emphasized header link, rendered as a button (.nav-btn in
     * src/styles/chrome.css, accent-filled by default).
     */
    headerCta: { label: "Articles", href: "/articles" } as SiteLink | null,

    /** Links inside the mobile slide-over menu. */
    mobile: [
      { label: "Projects", href: "/projects" },
      { label: "Images", href: "/images" },
      { label: "About", href: "/about" },
    ] as SiteLink[],
    /** The mobile menu's two call-to-action buttons. First is primary. */
    mobileCtas: [
      { label: "Articles", href: "/articles" },
      { label: "Get in touch", href: "mailto:j@jaan.io" },
    ] as SiteLink[],

    /** Footer link columns. Add or remove a column by adding or removing an array. */
    footer: [
      [
        { label: "Articles", href: "/articles" },
        { label: "Projects", href: "/projects" },
        { label: "Images", href: "/images" },
        { label: "About", href: "/about" },
      ],
    ] as SiteLink[][],
  },

  // ── The /about/ rail ───────────────────────────────────────────────────────
  // The tag rail in that page's left gutter (Toc.astro with `links` instead of
  // headings). Its own list rather than a slice of `social` below: the labels
  // are addressed to a reader mid-sentence ("email me", not "Email"), and it is
  // a deliberate shortlist — Flickr is in `social` and `sameAs` but not here.
  //
  // The X link points at x.com while `social` and `schema.sameAs` below still
  // say twitter.com. That is not drift: twitter.com/thejaan still redirects to
  // x.com/thejaan, this list is what a reader clicks, and sameAs is what search
  // engines have already associated with this person — worth leaving alone.
  contact: [
    { label: "EMAIL ME", href: "mailto:j@jaan.io" },
    { label: "GITHUB", href: "https://github.com/altosaar", external: true },
    { label: "LINKEDIN", href: "https://www.linkedin.com/in/jaanaltosaar", external: true },
    { label: "X", href: "https://x.com/thejaan", external: true },
  ] as SiteLink[],

  // ── Social & contact ───────────────────────────────────────────────────────
  // Rendered as the footer's second column. Overlaps `sameAs` below on purpose:
  // this list is what humans click, `sameAs` is what search engines read.
  social: [
    { label: "Email", href: "mailto:j@jaan.io" },
    { label: "GitHub", href: "https://github.com/altosaar", external: true },
    { label: "Twitter", href: "https://twitter.com/thejaan", external: true },
    { label: "LinkedIn", href: "https://www.linkedin.com/in/jaanaltosaar", external: true },
    { label: "Flickr", href: "https://www.flickr.com/photos/thejaan/", external: true },
  ] as SiteLink[],

  // ── Footer tail ────────────────────────────────────────────────────────────
  footer: {
    /** Legal/terms links, shown above the copyright. */
    legal: [] as SiteLink[],
    /** Rendered as "© {copyright} {current year}". */
    copyright: "Jaan Altosaar",
    /** Optional sign-off line. Set to "" to omit. */
    madeWith: "Brooklyn, New York",
    /**
     * Attribution for the mark, when the mark is someone else's work.
     *
     * NULL, and it should stay null while the favicons are what they are. They
     * used to be a vector of Nuna Parr's sculpture "Dancing Bear", which was
     * borrowed and had to be credited; they are now the portrait glyphs in
     * public/favicons/, derived from this site's own photographs by
     * scripts/gen-favicons.mjs. Nothing to credit but the camera.
     *
     * If it is ever set again it renders in the footer, so it appears on every
     * route except the home page, whose single-screen composition drops the
     * footer entirely (see `footer` in src/layouts/Base.astro).
     */
    credit: null as { prefix: string; label: string; href: string } | null,
  },

  // ── Structured data (JSON-LD) ──────────────────────────────────────────────
  // Emitted on every page by src/layouts/Base.astro so search and AI engines
  // know who publishes this site.
  schema: {
    /** schema.org type: "Organization", "NGO", "Person", "LocalBusiness", … */
    type: "Person",
    /** Path to the logo image used in structured data (absolutized at build). */
    logo: "/favicon.png",
    /** Optional — drop the line if the site isn't geographically scoped. */
    areaServed: "",
    /** Profile URLs that identify this same entity elsewhere. */
    sameAs: [
      "https://github.com/altosaar",
      "https://twitter.com/thejaan",
      "https://www.linkedin.com/in/jaanaltosaar",
      "https://www.flickr.com/photos/thejaan/",
      "https://www.onefact.org/",
    ],
  },

  // ── Feature switches ───────────────────────────────────────────────────────
  // Everything here can be turned off without touching any other file.
  features: {
    /**
     * The scrolling stats ticker across the top of the header.
     * Removed on this site — SiteHeader.astro no longer renders one and
     * src/data/stats.* was never copied over. Kept false for clarity.
     */
    ticker: false,
    /**
     * Shuffle the gallery into a new random order on every build.
     *
     * ON here. These are portraits with no argument running between them — no
     * chronology, no series, no first among them — so any fixed order is one
     * a viewer reads meaning into that was never put there. Off → the photos
     * appear in filename order, which is the order they happened to be
     * processed in and means even less. See src/data/gallery.ts.
     */
    randomizeGallery: true,
    /**
     * Pick a random gallery photo for the social share (Open Graph) image.
     * Off here: the share image is the portrait in src/lib/og.ts, not a
     * gallery photo, so this switch is inert. See that file.
     */
    randomizeOgImage: false,
    /**
     * The morphing portrait mark in the mobile nav bar.
     *
     * A TEST — flip this to false and it is gone: no markup, no request, no
     * layout change. Nothing else needs touching, and public/nav-morph.svg can
     * stay where it is (unreferenced, so it never ships to a visitor).
     *
     * What it is: public/nav-morph.svg, the faceglyph pipeline's morph — seven
     * paths whose SMIL animation walks each one through every portrait in the
     * set, so the mark is slowly dissolving from one face into the next. The
     * loop never ends, which is what lets each page load enter it on a
     * different face — see src/lib/nav-morph.ts. Generated by
     * scripts/gen-favicons.mjs.
     *
     * WHY MOBILE ONLY: it is offered as a replacement for what a phone loses,
     * not as an addition. Below 1024px .nav-links collapses into the menu
     * button (src/styles/chrome.css) and the bar goes nearly empty — that is
     * where a mark has room and a job. On desktop the bar is already full.
     *
     * ON DESKTOP it is a hover reward rather than a fixture: above 1024px the
     * bar is already full, so the mark waits behind the wordmark and slides
     * out to its right when the name is hovered or focused, sliding back
     * under it on leave. The morph itself is not even fetched until that
     * first hover.
     *
     * The 1024px figure lives in three places that must agree: the @media
     * block in chrome.css that shows the mark outright, the
     * (min-width: 1025px) block just below it that builds the hover reveal,
     * and the width test in src/lib/nav-morph.ts that decides whether to fetch
     * the morph on sight or wait for a pointer. All three carry a comment
     * pointing here and at each other.
     */
    navMorph: true,
  },
} as const;
