// GENERATED by scripts/gen-favicons.mjs — do not edit.
//
// One entry per portrait in public/favicons/. The daily picker that reads
// this list lives in src/lib/favicon.ts.
export const FAVICON_GLYPHS = [
  "230127-dsc09597",
  "dsc00341-resized",
  "dsc01149",
  "dsc01648",
  "dsc01666",
  "dsc01997-kakuyon",
  "dsc04539",
  "dsc05549",
  "dsc05563",
  "dsc05746",
  "dsc05961-3504",
  "dsc06911-3504",
  "bigbabyenergy-2022-07-24t183550-000z",
  "instagram-version",
] as const;
