// GENERATED by scripts/gen-favicons.mjs — do not edit.
//
// One entry per portrait in public/favicons/. The daily picker that reads
// this list lives in src/lib/favicon.ts.
export const FAVICON_GLYPHS = [
  "20210101-21-44-11-dsc02013-3456",
  "20260322-dsc00758",
  "20260418-dsc01222",
  "20260418-dsc01475",
  "20260419-dsc02559-edit-smaller",
  "221218-dsc08956-5",
  "dsc00181-3456",
  "dsc00192-3840",
  "dsc00201-3456",
  "dsc01109",
  "dsc02635",
  "dsc03884",
  "dsc05193-3456",
  "dsc05961-3504",
  "dsc06247",
  "dsc07196-3504",
  "dsc09673-3504",
  "chef",
  "sophie-and-david-copy",
  "sophie-and-david",
] as const;
