// GENERATED by scripts/gen-favicons.mjs — do not edit.
//
// One entry per portrait in public/nav-morph.svg: the second, within that
// file's 133s loop, at which the portrait stops dissolving and holds.
// The script that picks one per page load lives in src/lib/nav-morph.ts.
export const MORPH_FRAME_OFFSETS = [
  0, 7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98, 105, 112, 119, 126,
] as const;
