// The /visualizations index, in the order it is read.
//
// Seven are ported from jaan.li, an Observable Framework site whose sidebar
// listed them under "Visualizations". Their paths are the ones that site
// served, moved under /visualizations — so /glucose became
// /visualizations/glucose, and the four American Community Survey pages kept
// their nesting. jaan.li is not resolving today, so none of these are live URLs
// that need redirecting; this is a port of the source, not of a running site.
//
// The eighth, hospital-prices, comes from payless.health/hospital/nyu-langone —
// one of ten hospital dashboards there, and the only one reproduced here. That
// site IS live, so this is a copy rather than a rescue, and the page links back
// to the rest.

export interface Visualization {
  /** Path under /visualizations, without a leading or trailing slash. */
  slug: string;
  title: string;
  /** One line for the index. Says what is IN the data, not what it looks like. */
  blurb: string;
  /**
   * Scale of the underlying dataset.
   *
   * No longer shown on the index — that page is a mark, a headline and a line
   * now, and a third line of small caps under every one of eight entries was
   * more furniture than information. Still read by the "rest of this set" list
   * on src/pages/visualizations/american-community-survey.astro, where it is
   * the only thing distinguishing four entries with near-identical titles.
   */
  scale: string;
  /**
   * Basename of the mark drawn beside this entry on the index, generated by the
   * matching data loader in viz/src/thumbs and inlined by the index page. Not
   * derived from `slug`: the two ACS sub-pages would collide on a flat filename,
   * and a mark is a drawing of a dataset rather than a property of a URL.
   */
  thumb: string;
}

export const VISUALIZATIONS: Visualization[] = [
  {
    slug: "hospital-prices",
    title: "What one hospital charges",
    blurb:
      "Every price NYU Langone Tisch publishes, as the lowest against the highest rate negotiated for the same procedure. Points on the red diagonal cost everyone the same; almost none of them do.",
    scale: "28,101 procedures \u00b7 319 insurers",
    thumb: "hospital-prices",
  },
  {
    slug: "synthetic-healthcare-data",
    title: "Synthetic healthcare data",
    blurb:
      "What an inpatient claim actually gets paid, and how far that differs between commercial insurance, Medicaid and Medicare. Built on the Agency for Healthcare Research and Quality's synthetic discharge data.",
    scale: "1.2 million people · $8.6bn in claims",
    thumb: "synthetic-healthcare-data",
  },
  {
    slug: "new-york-real-estate",
    title: "New York real estate",
    blurb:
      "Every tax lot in New York City, drawn from the Department of City Planning's MapPLUTO extract. Hover any parcel for the full record the city holds on it, or click to pin it open.",
    scale: "850,000 properties",
    thumb: "new-york-real-estate",
  },
  {
    slug: "glucose",
    title: "Glucose levels over time",
    blurb:
      "Blood glucose readings across intensive-care stays, cross-filtered against the diagnostic category the patient was admitted under. Brush the heatmap or select a category and the other view follows.",
    scale: "150,000 people · 300,000 hospitalizations",
    thumb: "glucose",
  },
  {
    slug: "american-community-survey",
    title: "American Community Survey, 2022",
    blurb:
      "Two distributions from the most recent survey year: annual income by sector of employment, and monthly rent by region of the United States.",
    scale: "2022 · nationwide",
    thumb: "american-community-survey",
  },
  {
    slug: "american-community-survey/income",
    title: "Two decades of American incomes",
    blurb:
      "The same income distribution, scrubbed year by year from 2000 to 2022, showing how the ranking of sectors by pay has rearranged itself over twenty years.",
    scale: "38 million people · 2000–2022",
    thumb: "acs-income",
  },
  {
    slug: "american-community-survey/new-york-area",
    title: "New York incomes by area and sector",
    blurb:
      "Income by sector for any public use microdata area in the New York–Newark–Jersey City statistical area, in any year since 2005. Two neighbourhoods a mile apart can look nothing alike.",
    scale: "15 million people · 2005–2022",
    thumb: "acs-new-york-area",
  },
  {
    slug: "american-community-survey/income-by-race",
    title: "New York incomes by area and race",
    blurb: "The same areas and the same years, split by self-reported race rather than by sector.",
    scale: "15 million people · 2005–2022",
    thumb: "acs-income-by-race",
  },
];
